services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - media_files:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python create_superuser.py &&
             python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      - SILICONFLOW_BASE_URL=${SILICONFLOW_BASE_URL:-https://api.siliconflow.cn/v1}
      - MODEL_NAME=${MODEL_NAME:-Qwen/Qwen2.5-7B-Instruct}
      - DJANGO_LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - GENERATE_SOURCEMAP=false

  agent:
    build: ./ai-news-agent
    volumes:
      - ./ai-news-agent:/app
    ports:
      - "5001:5001"
    env_file:
      - ./.env
    depends_on:
      - backend
    command: python api_server.py
    restart: unless-stopped
    environment:
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      - SILICONFLOW_BASE_URL=${SILICONFLOW_BASE_URL:-https://api.siliconflow.cn/v1}
      - MODEL_NAME=${MODEL_NAME:-Qwen/Qwen2.5-7B-Instruct}

volumes:
  postgres_data:
  media_files:
