version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             gunicorn ai_news_backend.wsgi:application --bind 0.0.0.0:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  agent:
    build: ./ai-news-agent
    volumes:
      - ./ai-news-agent:/app
    ports:
      - "5001:5001"
    env_file:
      - ./.env
    depends_on:
      - backend
    command: python api_server.py
    restart: unless-stopped

volumes:
  postgres_data:
