# 开发环境专用的Docker Compose配置
# 使用方法: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python create_superuser.py &&
             python manage.py runserver 0.0.0.0:8000 --settings=ai_news_backend.settings"
    environment:
      - DEBUG=True
      - DJANGO_LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - media_files:/app/media

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm start
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3001
      - DOCKER_ENV=true
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules

  agent:
    command: python api_server.py
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      - SILICONFLOW_BASE_URL=${SILICONFLOW_BASE_URL:-https://api.siliconflow.cn/v1}
      - MODEL_NAME=${MODEL_NAME:-Qwen/Qwen2.5-7B-Instruct}
      - BACKEND_BASE_URL=${BACKEND_BASE_URL:-http://backend:8000}
      - BACKEND_API_TOKEN=${BACKEND_API_TOKEN:-}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEFAULT_MODEL_PROVIDER=${DEFAULT_MODEL_PROVIDER:-siliconflow}
      - DEFAULT_MODEL_ID=${DEFAULT_MODEL_ID:-Qwen/Qwen2.5-7B-Instruct}
    volumes:
      - ./ai-news-agent:/app
      - ./ai-news-agent/logs:/app/logs
    ports:
      - "5001:5001"
    depends_on:
      - backend
    # 开发环境下的额外配置
    stdin_open: true
    tty: true
    # 开发环境下允许热重载
    restart: "no"

volumes:
  media_files:
