# Generated by Django 5.2.5 on 2025-08-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_add_model_info_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='api_key',
            field=models.TextField(blank=True, null=True, verbose_name='API密钥'),
        ),
    ]
