# Generated by Django 5.2.5 on 2025-08-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='FetchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_date', models.DateField(verbose_name='获取日期')),
                ('news_count', models.PositiveIntegerField(default=0, verbose_name='新闻数量')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], max_length=20, verbose_name='状态')),
                ('log_message', models.TextField(blank=True, verbose_name='日志信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '获取历史',
                'verbose_name_plural': '获取历史',
                'ordering': ['-fetch_date', '-created_at'],
                'unique_together': {('fetch_date',)},
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('source', models.CharField(max_length=200, verbose_name='来源')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('url', models.URLField(blank=True, null=True, verbose_name='链接')),
                ('category', models.CharField(choices=[('tech_breakthrough', '技术突破'), ('product_release', '产品发布'), ('industry_news', '行业动态'), ('policy_regulation', '政策法规'), ('research_progress', '研究进展'), ('application_case', '应用案例'), ('other', '其他')], default='other', max_length=50, verbose_name='分类')),
                ('importance', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='重要程度')),
                ('key_points', models.JSONField(default=list, verbose_name='关键点')),
                ('timestamp', models.DateTimeField(verbose_name='新闻时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '新闻条目',
                'verbose_name_plural': '新闻条目',
                'ordering': ['-timestamp', '-created_at'],
                'indexes': [models.Index(fields=['-timestamp'], name='news_newsit_timesta_4cab22_idx'), models.Index(fields=['category'], name='news_newsit_categor_428b0a_idx'), models.Index(fields=['importance'], name='news_newsit_importa_16226c_idx')],
            },
        ),
    ]
