# Generated by Django 5.2.5 on 2025-08-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fetchhistory',
            options={'ordering': ['-created_at', '-fetch_date'], 'verbose_name': '获取历史', 'verbose_name_plural': '获取历史'},
        ),
        migrations.AlterUniqueTogether(
            name='fetchhistory',
            unique_together=set(),
        ),
    ]
